version: '3.4'

services:

  mongoIOT:
    container_name: mongoIOT
    image: mongo:latest
    restart: always
    volumes:
      - ./IOTDB/db:/data/db
    ports:
      - "27017:27017"

  webapiiot:
    image: ${DOCKER_REGISTRY-}webapiiot
    build:
      context: .
      dockerfile: WebApiIOT/Dockerfile
    depends_on:
      - mongoIOT
    links:
      - mongoIOT

  webapplicationiot:
    image: ${DOCKER_REGISTRY-}webapplicationiot
    build:
      context: .
      dockerfile: WebApplicationIOT/Dockerfile
    depends_on:
      - webapiiot
    links:
      - webapiiot

  mqttbroker:
    image: ${DOCKER_REGISTRY-}mqttbroker
    build:
      context: .
      dockerfile: MQTTBroker/Dockerfile
    ports:
      - "1883:1883"
    depends_on:
      - mongoIOT
    links:
      - mongoIOT

