version: '3.4'

services:

  mongoIOT:
    container_name: mongoIOT
    image: mongo:latest
    restart: always
    volumes:
      - ./IOTDB/db:/data/db
    ports:
      - "27017:27017"

  webapiiot:
    image: ${DOCKER_REGISTRY-}webapiiot
    build:
      context: .
      dockerfile: WebApiIOT/Dockerfile
    depends_on:
      - mongoIOT
    links:
      - mongoIOT

  mqttbroker:
    image: ${DOCKER_REGISTRY-}mqttbroker
    build:
      context: .
      dockerfile: MQTTBroker/Dockerfile
    ports:
      - "1883:1883"
    depends_on:
      - mongoIOT
    links:
      - mongoIOT

  reactiot:
    container_name: reactiot
    build:
        context: ./frontiot-react
        dockerfile: Dockerfile
    volumes:
      - './frontiot-react:/app'
      - '/app/node_modules'
    ports:
      - 80:3000
