version: '3.4'

services:
  mongoApp:
    container_name: mongoApp
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - "27017:27017"
  apirobot:
    image: ${DOCKER_REGISTRY-}apirobot
    build:
      context: .
      dockerfile: APIRobot/Dockerfile
